CashBox/PayUp.Console/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class CustomersController : Controller
    {
        string id;
        private readonly PayUpEntities db = new PayUpEntities();
        // GET: Customers
        public ActionResult YourCustomers()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;

            return View();
        }

        [HttpGet]
        public JsonResult GetCustomers()
        {
            var customers = (from x in db.Customers
                             where x.MerchantID == this.id
                             select new
                             {
                                 CustomerName = x.CustomerName,
                                 CustomerPhoneNo = x.PhoneNo,
                                 CustomerEmail = x.Email,
                                 Date = x.DateAdded,
                                 CustomerID = x.CustomerID
                             }).ToList();

            return Json(new { data = customers }, JsonRequestBehavior.AllowGet);
        }
    }
}

CashBox/PayUp.Console/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class MerchantController : Controller
    {
        string id;
        double balanceSummation;
        private readonly PayUpEntities db = new PayUpEntities();
        // GET: Dashboard
        public ActionResult Dashboard()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }
            GlobalData global = new GlobalData();

            this.id = GlobalData.getUserIDFromApplication;

            var FullName = db.Registrations.Where(x => x.RegistrationID.ToString() == this.id).Select(x => x.BusinessName).FirstOrDefault().ToString();

            var modeType = db.ApiKeys.Where(x => x.MerchantID == this.id && x.isLiveMode == true).Count();

            //If in live mode, get live transactions
            if(modeType > 0)
            {
                var Balance = db.LiveTransactions.Where(x => x.MerchantID == this.id && x.ResponseCode == "0").Select(x => x).ToList();

                this.balanceSummation = Balance.Sum(x => Convert.ToDouble(x.Amount));
            }
            else
            {
                //else get test transactions
                var Balance = db.TestTransactions.Where(x => x.MerchantID == this.id && x.ResponseCode == "0").Select(x => x).ToList();

                this.balanceSummation = Balance.Sum(x => Convert.ToDouble(x.Amount));
            }    

            global.setCurrentBalanceFromApplication(this.balanceSummation.ToString());

            global.setFullNameFromApplication(FullName);
            
            return View();
        }         
        
    }
}

CashBox/PayUp.Console/Controllers/DeveloperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class DeveloperController : Controller
    {
        public  string id;
        public string secreteKey, publicKey;
        RandomGenerator generator;
        private readonly PayUpEntities db = new PayUpEntities();

        // GET: Developer
        public ActionResult ApiDetails()
        {

            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;

            var devKeys = db.ApiKeys.Where(x => x.MerchantID == this.id).Select(x => x).FirstOrDefault();

            if(devKeys != null)
            {
                ViewBag.TestSecretekey = devKeys.TestPrivateKey.Trim();

                ViewBag.TestPublickey = devKeys.TestPublicKey.Trim();

                ViewBag.LiveSecretekey = devKeys.LivePrivateKey;

                ViewBag.LivePublickey = devKeys.LivePublicKey;
            }

            return View();
        }

        public void generateTestKeys(string email)
        {
            this.secreteKey = string.Concat("sk_test_", generator.generateSequence(12)); 

            this.publicKey = string.Concat("pk_test_", generator.generateSequence(17));

            var merchantID = db.Registrations.Where(x => x.Email == email).Select(x => x.RegistrationID).FirstOrDefault();


            var keys = new ApiKey()
            {
                TestPrivateKey = this.secreteKey,

                TestPublicKey = this.publicKey,

                MerchantID = merchantID.ToString(),

                isLiveMode = false,
            };

            db.ApiKeys.Add(keys);

            db.Entry(keys).State = System.Data.Entity.EntityState.Added;

            db.SaveChanges();
        }
    }
}

CashBox/PayUp.Console/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class InvoiceController : Controller
    {

       public string id;

        private readonly PayUpEntities db = new PayUpEntities();

        // GET: Invoice
        public ActionResult PaymentRequest()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;

            return View();
        }


        [HttpGet]
        public JsonResult GetPaymentRequests()
        {
            var paymentReq = (from x in db.Invoices
                              where x.MerchantID == this.id
                              select new
                              {
                                  Status = x.Status,
                                  RequestedOn = x.DateRequested,
                                  From = x.RequestedBy,
                                  Amount = x.Amount,
                                  PDF = x.isAttachmentAllowed,
                                  InvoiceID = x.InvoiceID
                              }).ToList();

            object paymentResp = new
            {

            };

            foreach(var pay in paymentReq)
            {
                var docName = db.InvoiceAttachments.Where(x => x.InvoiceID == pay.InvoiceID.ToString()).Select(x => x.DocName).FirstOrDefault();

                paymentResp = new
                {
                    Status = pay.Status,
                    RequestedOn = pay.RequestedOn,
                    From = pay.From,
                    Amount = pay.Amount,
                    PDF = docName,
                    InvoiceID = pay.InvoiceID
                };
            };

            return Json(new { data = paymentReq}, JsonRequestBehavior.AllowGet);
           
        }
    }
}

CashBox/PayUp.Console/Controllers/PayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class PayoutController : Controller
    {

        private readonly PayUpEntities db = new PayUpEntities();
        string id;
        // GET: PayUp
        public ActionResult Settlement()
        {

            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;


            var BusinessName = db.BusinessProfiles.Where(x => x.MerchantID == id).Select(x => x.BusinessName).FirstOrDefault();

            var BankDetails = db.SettlementDetails.Where(x => x.MerchantID.ToString() == id).Select(x => x).FirstOrDefault();

            if(BankDetails != null)
            {
                ViewBag.AccountNo = BankDetails.AccountNo.Trim();

                ViewBag.BankName = BankDetails.BankName.Trim();

                ViewBag.BusinessName = BusinessName.Trim();
            }
            else
            {
                ViewBag.AccountNo = "UnKnown";

                ViewBag.BankName = "UnKnown";

                ViewBag.BusinessName = "UnKnown";
            }
            return View();
        }

        [HttpGet]
        public JsonResult GetSettlements()
        {
            try
            {
                var settlements = (from x in db.Payouts
                                   where x.MerchantID == this.id
                                   select new
                                   {
                                       Status = x.Status,
                                       Amount = x.Amount,
                                       TotalTransactions = x.TotalTransactions,
                                       RequestCode = x.RequestCode,
                                       SettlementDate = x.SettlementDate
                                   }).ToList();

                return Json(new { data = settlements }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception)
            {
                throw;
            }
        }
    }
}

CashBox/PayUp.Console/Views/Merchant/Dashboard.cshtml
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../favicon1.ico">

    <title>CashBox</title>

    <!--  RESET STYLES  -->
    <link href="../Theme/css/reset.css" rel="stylesheet">

    <!-- Core CSS -->
    <link href="../Theme/css/lib/metro-bootstrap.min.css" rel="stylesheet">
    <link href="../Theme/css/lib/bootstrap.min.css" rel="stylesheet">

    <!--  Slider Style  -->
    <link rel="stylesheet" href="../Theme/css/bjqs.css">

    <!-- Custom CSS -->
    <link href="../Theme/css/style.css" rel="stylesheet">

    <!--  Js Library  -->
    <script src="../Theme/js/lib/jquery-2.1.1.js"></script>

    <!-- Modernizr -->
    <script src="../Theme/js/modernizr.js"></script>

    <!--  Slider Js  -->
    <script src="../Theme/js/lib/bjqs-1.3.min.js"></script>

    <script class="secret-source">
        jQuery(document).ready(function ($) {

            $('#slider-section').bjqs({
                //            animtype      : 'slide',
                height: 310,
                width: 630,
                nexttext: '<i class="fa fa-angle-double-right"></i>', // Text for 'next' button (can use HTML)
                prevtext: '<i class="fa fa-angle-double-left"></i>', // Text for 'previous' button (can use HTML)
                responsive: true
            });

        });
    </script>

    <script>
        function comingSoon() {
            alert('This feature is coming soon');
        }
    </script>


</head>


<body style="background-color: #A599B5; background-image: url('../Theme/images/bg/7.jpg'); background-repeat: no-repeat; background-size: cover; background-position: fixed;">


    <section class="Default-lite">

        <div class="container">

            <header>

                <div class="col-md-9 no-padleft">
                    <a href="#" class="logo">
                        <img src="../Theme/images/kudikonnect-logo.png" />
                    </a>
                </div>

                <div class="col-md-3">             

                    @if (PayUp.Core.Utility.GlobalData.getUserIDFromApplication != null)
                    {
                        <a href="@Url.Action("SignOut", "Account")" class="btn btn-warning marg-left-10 radius-20"> Sign Out <i class="fa fa-sign-out"></i></a>
                    }
                    else
                    {
                    <a href="@Url.Action("Login", "Account")" class="btn btn-warning marg-left-10 radius-20"> Sign In <i class="fa fa-sign-in"></i></a>
                    }

                    <div class="dropdown pull-right marg-left-10">
                        <button class="btn btn-default radius-20 dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-user"></span>Profile<span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="/TransactionLogs/Index">@ViewBag.FullName</a></li>
                            <li><a href="@Url.Action("MyProfile","Account")">Edit Profile</a></li>
                            <li><a href="@Url.Action("ForgotPassword","Account")">Change password</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("SignOut","Account")">Sign Out</a></li>
                        </ul>
                    </div>

                </div>

            </header>

            <div class="featured-apps">

                <div class="tile tile-medium tile-deep-plum">
                    <a href="@Url.Action("Logs","TransactionLogs")" class="fa-links">
                        <span><img src="~/Theme/images/apps/payment.png"></span>
                        <h2>Transactions Logs</h2>
                    </a>
                </div>
                <div class="tile tile-medium tile-deep-dodgerblue">
                    <a href="@Url.Action("Settlement","Payout")" class="fa-links">
                        <span><img src="~/Theme/images/apps/payout.png"></span>
                        <h2>Settlement</h2>
                    </a>
                </div>
                <div class="tile tile-medium tile-deep-indigo">
                    <a href="@Url.Action("YourCustomers","Customers")" class="fa-links">
                        <span><img src="~/Theme/images/apps/customer.png"></span>
                        <h2>Customers</h2>
                    </a>
                </div>

                <div class="tile tile-medium tile-deep-orange">
                    <a href="@Url.Action("Plans","Subscriptions")" class="fa-links">
                        <span><img src="~/Theme/images/apps/subscriptions.png"></span>
                        <h2>Subsriptions</h2>
                    </a>
                </div>

                <div class="tile tile-wide tile-blue">
                    <a href="@Url.Action("Logs","TransactionLogs")" class="fa-links">
                        <span><img src="../Theme/images/apps/sign-up.png" /></span>
                        <h2>Hello! <strong>@PayUp.Core.Utility.GlobalData.getFullNameFromApplication</strong> <br>Total Amount Accrued: ₦@PayUp.Core.Utility.GlobalData.getCurrentBalanceFromApplication</h2>
                    </a>
                </div>

                <!-- <div class="tile tile-wide tile-blue">
                    <a href="#" class="fa-links">
                        <span><img src="images/apps/sign-in.png" /></span>
                        <h3>09092152863 <br/> Current balance: &#8358;2,000</h3>
                    </a>
                </div>  -->

                <div class="tile tile-medium tile-teal">
                    <a href="@Url.Action("Product","ProductPage")">
                        <span><img src="../Theme/images/apps/product.png" /></span>
                        <h3>Product Page</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-concrete">
                    <a href="@Url.Action("Page","PaymentPage")">
                        <span><img src="../Theme/images/apps/paymentpage.png" /></span>
                        <h3>Payment Page</h3>
                    </a>
                </div>           

                <div class="tile tile-medium tile-yellow">
                    <a href="@Url.Action("PaymentRequest","Invoice")">
                        <span><img src="../Theme/images/apps/my-invoice.png" /></span>
                        <h3>Invoice</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-green">
                    <a href="@Url.Action("Index","Connect")">
                        <span><img src="../Theme/images/apps/connect.png" /></span>
                        <h3>Connect</h3>
                    </a>
                </div>


                <div class="tile tile-medium tile-green-sea">
                    <a href="@Url.Action("ApiDetails","Developer")">
                        <span><img src="../Theme/images/apps/API.png" /></span>
                        <h3>API Keys</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-blue">
                    <a href="#">
                        <span><img src="../Theme/images/apps/migration.png" /></span>
                        <h3 style="font-size:17px">Account Migration</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-green">
                    <a href="#" onclick="comingSoon()">
                        <span><img src="../Theme/images/apps/documentations.png" class="app-refactor" /></span>
                        <h3>API Documentation</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-orange">
                    <a href="@Url.Action("Users","TeamMembers")">
                        <span><img src="../Theme/images/apps/accountusers.png"></span>
                        <h3>Account Users</h3>
                    </a>
                </div>

                <div class="tile tile-medium tile-deep-rebeccapurple">
                    <a href="@Url.Action("Setup","Configuration")">
                        <span><img src="~/Theme/images/apps/configuration.png"></span>
                        <h2>Configuration</h2>
                    </a>
                </div>

                <div class="tile tile-medium tile-deep-hotpink">
                    <a href="@Url.Action("Index","Analytics")">
                        <span><img src="~/Theme/images/apps/analytics.png"></span>
                        <h2>Analytics</h2>
                    </a>
                </div>
                
                <div class="tile tile-medium tile-deep-lightslategray">
                    <a href="#" class="fa-links">
                        <span><img src="~/Theme/images/apps/bitcoin.png"></span>
                        <h2>Crypto Currency</h2>
                    </a>
                </div>

                <div class="tile tile-medium tile-deep-sandybrown">
                    <a href="#" class="fa-links">
                        <span><img src="~/Theme/images/apps/hotels.png"></span>
                        <h2>Book Hotels</h2>
                    </a>
                </div>

                <div class="tile tile-medium tile-deep-dodgerblue">
                    <a href="#" class="fa-links">
                        <span><img src="~/Theme/images/apps/ATM-Cash.png"></span>
                        <h2>ATM Withdrawals</h2>
                    </a>
                </div>

                <div class="tile tile-medium tile-wet-asphalt">
                    <a href="#">
                        <span style="height: 110px;"><img src="../Theme/images/apps/coming-soon-2.png" /></span>
                        <!-- <h3>Coming Soon</h3> -->
                    </a>
                </div>

                <div class="tile tile-medium tile-purple">
                    <a href="@Url.Action("Contact","Default")">
                        <span><img src="../Theme/images/apps/help-online.png" /></span>
                        <h3>Help and Support</h3>
                    </a>
                </div>


            </div>

        </div>

        <!-- Site footer -->
        <footer class="footer">
            <div class="container">
                <div class="col-md-12">
                    <p>&copy; Copyright @DateTime.Now.Year <a href="#" class="site-title">PayUp</a></p>
                </div>
            </div>
        </footer>

    </section>

    <script src="../Theme/js/lib/bootstrap.min.js"></script>
    @*<script src="//cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>*@

    <script>
        particlesJS();
    </script>
</body>

</html>