CashBox/PayUp.Console/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class CustomersController : Controller
    {
        string id;
        private readonly PayUpEntities db = new PayUpEntities();
        // GET: Customers
        public ActionResult YourCustomers()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;

            return View();
        }

        [HttpGet]
        public JsonResult GetCustomers()
        {
            var customers = (from x in db.Customers
                             where x.MerchantID == this.id
                             select new
                             {
                                 CustomerName = x.CustomerName,
                                 CustomerPhoneNo = x.PhoneNo,
                                 CustomerEmail = x.Email,
                                 Date = x.DateAdded,
                                 CustomerID = x.CustomerID
                             }).ToList();

            return Json(new { data = customers }, JsonRequestBehavior.AllowGet);
        }
    }
}

CashBox/PayUp.Console/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class MerchantController : Controller
    {
        string id;
        double balanceSummation;
        private readonly PayUpEntities db = new PayUpEntities();
        // GET: Dashboard
        public ActionResult Dashboard()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }
            GlobalData global = new GlobalData();

            this.id = GlobalData.getUserIDFromApplication;

            var FullName = db.Registrations.Where(x => x.RegistrationID.ToString() == this.id).Select(x => x.BusinessName).FirstOrDefault().ToString();

            var modeType = db.ApiKeys.Where(x => x.MerchantID == this.id && x.isLiveMode == true).Count();

            //If in live mode, get live transactions
            if(modeType > 0)
            {
                var Balance = db.LiveTransactions.Where(x => x.MerchantID == this.id && x.ResponseCode == "0").Select(x => x).ToList();

                this.balanceSummation = Balance.Sum(x => Convert.ToDouble(x.Amount));
            }
            else
            {
                //else get test transactions
                var Balance = db.TestTransactions.Where(x => x.MerchantID == this.id && x.ResponseCode == "0").Select(x => x).ToList();

                this.balanceSummation = Balance.Sum(x => Convert.ToDouble(x.Amount));
            }    

            global.setCurrentBalanceFromApplication(this.balanceSummation.ToString());

            global.setFullNameFromApplication(FullName);
            
            return View();
        }         
        
    }
}

CashBox/PayUp.Console/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class InvoiceController : Controller
    {

       public string id;

        private readonly PayUpEntities db = new PayUpEntities();

        // GET: Invoice
        public ActionResult PaymentRequest()
        {
            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;

            return View();
        }


        [HttpGet]
        public JsonResult GetPaymentRequests()
        {
            var paymentReq = (from x in db.Invoices
                              where x.MerchantID == this.id
                              select new
                              {
                                  Status = x.Status,
                                  RequestedOn = x.DateRequested,
                                  From = x.RequestedBy,
                                  Amount = x.Amount,
                                  PDF = x.isAttachmentAllowed,
                                  InvoiceID = x.InvoiceID
                              }).ToList();

            object paymentResp = new
            {

            };

            foreach(var pay in paymentReq)
            {
                var docName = db.InvoiceAttachments.Where(x => x.InvoiceID == pay.InvoiceID.ToString()).Select(x => x.DocName).FirstOrDefault();

                paymentResp = new
                {
                    Status = pay.Status,
                    RequestedOn = pay.RequestedOn,
                    From = pay.From,
                    Amount = pay.Amount,
                    PDF = docName,
                    InvoiceID = pay.InvoiceID
                };
            };

            return Json(new { data = paymentReq}, JsonRequestBehavior.AllowGet);
           
        }
    }
}

CashBox/PayUp.Console/Controllers/PayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayUp.Core.Utility;
using PayUp.Core.DB.STAGING;

namespace PayUp.Console.Controllers
{
    public class PayoutController : Controller
    {

        private readonly PayUpEntities db = new PayUpEntities();
        string id;
        // GET: PayUp
        public ActionResult Settlement()
        {

            // If session is empty redirect to login
            if (string.IsNullOrEmpty((string)GlobalData.getUerNameFromApplication))
            {
                return RedirectToAction("Index", "Default");
            }

            this.id = GlobalData.getUserIDFromApplication;


            var BusinessName = db.BusinessProfiles.Where(x => x.MerchantID == id).Select(x => x.BusinessName).FirstOrDefault();

            var BankDetails = db.SettlementDetails.Where(x => x.MerchantID.ToString() == id).Select(x => x).FirstOrDefault();

            if(BankDetails != null)
            {
                ViewBag.AccountNo = BankDetails.AccountNo.Trim();

                ViewBag.BankName = BankDetails.BankName.Trim();

                ViewBag.BusinessName = BusinessName.Trim();
            }
            else
            {
                ViewBag.AccountNo = "UnKnown";

                ViewBag.BankName = "UnKnown";

                ViewBag.BusinessName = "UnKnown";
            }
            return View();
        }

        [HttpGet]
        public JsonResult GetSettlements()
        {
            try
            {
                var settlements = (from x in db.Payouts
                                   where x.MerchantID == this.id
                                   select new
                                   {
                                       Status = x.Status,
                                       Amount = x.Amount,
                                       TotalTransactions = x.TotalTransactions,
                                       RequestCode = x.RequestCode,
                                       SettlementDate = x.SettlementDate
                                   }).ToList();

                return Json(new { data = settlements }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception)
            {
                throw;
            }
        }
    }
}

CashBox/PayUp.Console/Views/Shared/_Footer.cshtml
<!--
==============
    Footer
==============
-->
<footer class="bg-white">
    <div class="container py-5">
        <div class="row text-center">
            <div class="col-12 pb-3">
                <a target="_blank" href="https://twitter.com/PayUpNG" class="text-muted">
                    <h1 class="display-4 d-inline-flex"><i class="icon-twitter"></i></h1>
                </a>
                <a target="_blank" href="https://www.facebook.com/PayUpNG" class="text-muted ml-3">
                    <h1 class="display-4 d-inline-flex"><i class="icon-facebook"></i></h1>
                </a>
            </div>
            <div class="col-12">
                <p class="text-muted">&copy; Copright @DateTime.Now.Year PayUp.</p>
            </div>
        </div>
    </div>
</footer>

CashBox/PayUp.Console/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../favicon1.ico">

    <title>TapaPay - Make Safe Transactions</title>

    <!--  RESET STYLES  -->
    <link href="../Theme/css/reset.css" rel="stylesheet">

    <!-- Core CSS -->
    <link href="../Theme/css/lib/metro-bootstrap.min.css" rel="stylesheet">
    <link href="../Theme/css/lib/bootstrap.min.css" rel="stylesheet">

    <!-- Country Code Style -->
    <link rel="stylesheet" type="text/css" href="../Theme/css/flags.css">

    <!-- Mobile Menu Style -->
    <link rel="stylesheet" type="text/css" href="../Theme/css/mobile-menu-controller.css">

    <!-- Custom CSS -->
    <link href="../Theme/css/style.css" rel="stylesheet">

    <script src='../Theme/js/lib/slimscroll.js'></script>

    <script>
        window.onload = function () {
            var element = document.querySelectorAll('.slimScroll');

            // Apply slim scroll plugin
            var one = new slimScroll(element[0], {
                'wrapperClass': 'scroll-wrapper unselectable mac',
                'scrollBarContainerClass': 'scrollBarContainer',
                'scrollBarContainerSpecialClass': 'animate',
                'scrollBarClass': 'scroll',
                'keepFocus': true
            });
 
            window.onresize = function () {
                one.resetValues();
                two.resetValues();
                three.resetValues();
            }
        }
    </script>

    <script src="../Theme/js/modernizr.js"></script>

    <script src="../Theme/js/lib/jquery.mmenu.min.all.js"></script>


</head>




<body id="page" class="dashboard-bg cbp-spmenu-push">


    <section class="dashboard-lite content">

        <div class="container">
     
            <div class="row">
                <div class="inner-header">
                    <a href="@Url.Action("Dashboard","Merchant")">
                        <img src="../Theme/images/kudikonnect-logo.png" />
                    </a>
                    <div class="col-md-9 col-xs-12 pull-right">
                        <div class="search-box">
                            <form>
                                <input class="col-md-10" type="search" placeholder="Search Services" />
                                <button class="col-md-2"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        @if (PayUp.Core.Utility.GlobalData.getUserIDFromApplication != null)
                        {
                            <a href="@Url.Action("SignOut","Account")" class="btn btn-warning marg-left-10 radius-20 pull-right"> Sign Out <i class="fa fa-sign-in"></i></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login","Account")" class="btn btn-warning marg-left-10 radius-20 pull-right"> Sign In <i class="fa fa-sign-in"></i></a>
                        }


                        <div class="dropdown pull-right marg-left-10">
                            <button class="btn btn-default radius-20 dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="fa fa-user"></span> Profile <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="/TransactionLogs/Index">@ViewBag.FullName</a></li>
                                <li><a href="@Url.Action("MyProfile","Account")">Edit Profile</a></li>
                                <li><a href="@Url.Action("ForgotPassword","Account")">Change password</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("SingOut","Account")">Sign Out</a></li>
                            </ul>
                        </div>
                        <script>
                            function comingSoon() {
                                alert('Coming soon')
                            }
                        </script>

                    </div>
                </div>
            </div>
            <div class="row">

                @RenderBody()

                <div class="col-sm-4 app-sidebar-section slimScroll">
                    <!-- <div class="col-sm-4 app-sidebar-section"> -->

                    <div class="sidebar-module featured-apps">

                        <div class="tile tile-wide tile-blue">
                            <a href="@Url.Action("Logs","TransactionLogs")" class="fa-links">
                                <span><img src="../Theme/images/apps/sign-up.png" /></span>
                                <h2>Hello! <strong> @PayUp.Core.Utility.GlobalData.getFullNameFromApplication</strong> <br>Total Amount Accrued: ₦@PayUp.Core.Utility.GlobalData.getCurrentBalanceFromApplication</h2>
                            </a>
                        </div>



                        <div class="tile tile-medium tile-deep-orange">
                            <a href="@Url.Action("Logs","TransactionLogs")" class="fa-links">
                                <span><img src="../Theme/images/apps/payment.png" /></span>
                                <h3>My Transactions</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-concrete">
                            <a href="@Url.Action("Settlement","Payout")">
                                <span><img src="../Theme/images/apps/payout.png" /></span>
                                <h3>Payout</h3>
                            </a>
                        </div>


                        <div class="tile tile-medium tile-teal">
                            <a href="@Url.Action("YourCustomers","Customers")">
                                <span><img src="../Theme/images/apps/customer.png" /></span>
                                <h3>Customers</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-belize-hole">
                            <a href="@Url.Action("Product","ProductPage")">
                                <span><img src="../Theme/images/apps/product.png" /></span>
                                <h3>Product Page</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-orange">
                            <a href="@Url.Action("Page","PaymentPage")">
                                <span><img src="../Theme/images/apps/paymentpage.png"></span>
                                <h3>Payment Page</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-purple">
                            <a href="@Url.Action("Plans","Subscriptions")">
                                <span><img src="../Theme/images/apps/subscriptions.png" /></span>
                                <h3>Subscription</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-yellow">
                            <a href="@Url.Action("PaymentRequest","Invoice")">
                                <span><img src="../Theme/images/apps/my-invoice.png" /></span>
                                <h3>Invoice</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-blue">
                            <a href="#">
                                <span><img src="../Theme/images/apps/connect.png" /></span>
                                <h3>Connect</h3>
                            </a>
                        </div>


                        <div class="tile tile-medium tile-green-sea">
                            <a href="@Url.Action("ApiDetails","Developer")">
                                <span><img src="../Theme/images/apps/API.png" /></span>
                                <h3>API Keys</h3>
                            </a>
                        </div>

                        <div class="tile tile-medium tile-pumpkin">
                            <a href="#">
                                <span><img src="../Theme/images/apps/migration.png" /></span>
                                <h3>Account Migration</h3>
                            </a>
                        </div>

                      

                        <!--  <div class="tile tile-medium tile-red">
                             <a href="#">
                                 <span><img src="images/apps/help-online.png" /></span>
                                 <h3>Help</h3>
                             </a>
                         </div> -->

                    </div>

                </div><!-- /.app-sidebar -->

            </div>

        </div>

        <!-- Site footer -->
        <footer class="footer">
            <div class="container">
                <div class="col-md-8">
                    <p>&copy; Copyright @DateTime.Now.Year <a href="#" class="site-title">CashBox</a></p>
                </div>

                <div class="col-md-4 social-icons">
                    <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="google-plus" href="#"><i class="fa fa-google-plus"></i></a>
                    <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
        </footer>

    </section>



    <!-- // <script src="js/lib/bootstrap.min.js"></script> -->
    <script src="../Theme/js/classie.js"></script>
    <!-- // <script src="js/mobile-menu-controller.js"></script> -->

    <script src="../Theme/js/lib/bootstrap.min.js"></script>



</body>
</html>

CashBox/PayUp.Console/Views/Shared/_NavBar.cshtml
<!--
===============
    Navbar
===============
-->

<nav class="navbar navbar-toggleable-md navbar-inverse py-lg-0 custom-nav">
    <div class="container w-xs-100">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#pyNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand">
            <img src="~/cons/logo.svg" height="35" class="non-transparent" alt="">
            <img src="~/img/white.png" height="60" class="transparent" alt="">
        </a>
        <div class="collapse navbar-collapse" id="pyNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Default")">Default</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("PaymentGateway","Default")">PAYMENT GATEWAY</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Enterprise","Default")">ENTERPRISE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Developers","Default")">DEVELOPERS</a>
                </li>
                <a class="nav-item">
                    <a class="nav-link" href="http://www.medium.com/payconnect" target="_blank">SUPPORT</a>
                </a>
            </ul>
        </div>
    </div>
</nav>